### ISSUE TITLE
feat(fabric): Design Choices for One Organization-Multiple Cluster Deployments

### ISSUE THREAD

**Issue by arsulegai** [hyperledger/bevel#1847]
**Is your feature request related to a problem? Please describe.**
The feature is to enable running Hyperledger Fabric peers/orderers across multiple clusters. With the current design, the `K8s` section is tied to an organization within a `network.yaml` input configuration file. This makes it impossible to specify multiple clusters for the same organization peers/orderers.

One immediate alternate thought is to run multiple `network.yaml` against different clusters. But this too would fail given the nature of Hashicorp Vault works for K8s service account token based authentication and the way current Bevel deployments are designed to authenticate themselves against Vault.

Note that Vault authentication is one of many design changes one has to make to support the capability. For instance, one still has to look into how can they make GitOps from multiple clusters only worry about deployments those clusters should be working on.

**Describe the solution you'd like**
Support multi-cluster deployment for each organization. To be specific for Vault related issue, introduce a new layer/sub-env parameter that goes below network name, env in hierarchy. This parameter is unique per cluster. Together all these 3 parameters shall be used to identify the authentication information from the Vault.

**Describe alternatives you've considered**
Just say, for single organization in Bevel, multi-cluster deployment is not possible. Which basically means that the feature is not supported.

**Additional context**
None

**Comment by sownak** [comment]
@arsulegai So, as I understand the main issue is running single organisation on multiple Kubernetes clusters. 
The solution can be the following changes:

- Create an optional `identifier` for the cluster in `k8s` section since `context` can be too long
- Create the Vault auths with this identifier so that they are separate on Vault

**Comment by sownak** [comment]
Each cluster should have a separate branch for the deployment files. If that is not possible, the least they can do is write to separate directories. So, either use different `gitops.branch` or use different `gitops.release_dir` like `release_dir: "platforms/hyperledger-fabric/releases/cluster1"` and `release_dir: "platforms/hyperledger-fabric/releases/cluster2"`

**Comment by arsulegai** [comment]
It would be nice if you can propose the schema with `k8s`, `gitops` models alongside an `organization`, we can iterate over that for more questions.

**Comment by sownak** [comment]
Should be as below

```yaml
- organization:
      name: supplychain
      .
      .
      # Kubernetes cluster deployment variables. The config file path and name has to be provided in case
      # the cluster has already been created.
      k8s:
        cluster_id: "cluster1"
        context: "cluster_context"
        config_file: "cluster_config"
      .
      .
      # Git Repo details which will be used by GitOps/Flux.
      # Do not check-in git_access_token
      gitops:
        git_protocol: "https" # Option for git over https or ssh
        git_url: "https://github.com/<username>/bevel.git"         # Gitops https or ssh url for flux value files 
        branch: "develop"           # Git branch where release is being made
        release_dir: "platforms/hyperledger-fabric/releases/cluster1" # Relative Path in the Git repo for flux sync per environment. 
        chart_source: "platforms/hyperledger-fabric/charts"     # Relative Path where the Helm charts are stored in Git repo
        git_repo: "github.com/<username>/bevel.git"   # Gitops git repository URL for git push  (without https://)
        username: "git_username"          # Git Service user who has rights to check-in in all branches
        password: "git_access_token"          # Git Server user password/token (Optional for ssh; Required for https)
        email: "git@email.com"                # Email to use in git config
        private_key: "path_to_private_key"          # Path to private key file which has write-access to the git repo (Optional for https; Required for ssh)
    
```

**Comment by arsulegai** [comment]
I meant to ask the scheme for the solution proposal. The current schema as can be seen, neither allow for one organisation to specify different release directories for different clusters, nor allow to add multiple clusters for each organisation.

**Comment by sownak** [comment]
Yes so for multiple clusters on same organization, the configuration files need to be separate. So, a different file called `cluster2.yaml` will have this
```yaml
- organization:
      name: supplychain
      .
      .
      # Kubernetes cluster deployment variables. The config file path and name has to be provided in case
      # the cluster has already been created.
      k8s:
        cluster_id: "cluster2"
        context: "cluster_context"
        config_file: "cluster_config"
      .
      .
      # Git Repo details which will be used by GitOps/Flux.
      # Do not check-in git_access_token
      gitops:
        git_protocol: "https" # Option for git over https or ssh
        git_url: "https://github.com/<username>/bevel.git"         # Gitops https or ssh url for flux value files 
        branch: "develop"           # Git branch where release is being made
        release_dir: "platforms/hyperledger-fabric/releases/cluster2" # Relative Path in the Git repo for flux sync per environment. 
        chart_source: "platforms/hyperledger-fabric/charts"     # Relative Path where the Helm charts are stored in Git repo
        git_repo: "github.com/<username>/bevel.git"   # Gitops git repository URL for git push  (without https://)
        username: "git_username"          # Git Service user who has rights to check-in in all branches
        password: "git_access_token"          # Git Server user password/token (Optional for ssh; Required for https)
        email: "git@email.com"                # Email to use in git config
        private_key: "path_to_private_key"          # Path to private key file which has write-access to the git repo (Optional for https; Required for ssh)
 
```
Of course, additional clusters have to be added after the genesis network has been created by using `add-orderer.yaml` or `add-peer.yaml` playbooks.
